#French Words List
fre_words = ['comme', 'je', 'son', 'que', 'il', 'était', 'pour', 'sur', 'sont', 'avec', 'ils',
             'être', 'à', 'un', 'avoir', 'ce', 'à partir de', 'par', 'chaud', 'mot', 'mais', 
             'que', 'certains', 'est', 'il', 'vous', 'ou', 'eu', 'la', 'de', 'à', 'et', 'un', 
             'dans', 'nous', 'boîte', 'dehors', 'autre', 'étaient', 'qui', 'faire', 'leur', 
             'temps', 'si', 'volonté', 'comment', 'dit', 'un', 'chaque', 'dire', 'ne', 'ensemble', 
             'trois', 'vouloir', 'air', 'bien', 'aussi', 'jouer', 'petit', 'fin', 'mettre', 'maison', 
             'lire', 'main', 'port', 'grand', 'épeler', 'ajouter', 'même', 'terre', 'ici', 'il faut', 
             'grand', 'haut', 'tel', 'suivre', 'acte', 'pourquoi', 'interroger', 'hommes', 'changement', 
             'est allé', 'lumière', 'genre', 'de', 'besoin', 'maison', 'image', 'essayer', 'nous', 'encore', 
             'animal', 'point', 'mère', 'monde', 'près de', 'construire', 'soi', 'terre', 'père', 'tout', 
             'nouveau', 'travail', 'partie', 'prendre', 'obtenir', 'lieu', 'fabriqué', 'vivre', 'où', 
             'après', 'arrière', 'peu', 'seulement', 'tour', 'homme', 'année', 'est venu', 'montrer', 
             'tous', 'bon', 'moi', 'donner', 'notre', 'sous', 'nom', 'très', 'par', 'juste', 'forme', 
             'phrase', 'grand', 'penser', 'dire', 'aider', 'faible', 'ligne', 'différer', 'tour', 
             'la cause', 'beaucoup', 'signifier', 'avant', 'déménagement', 'droit', 'garçon', 
             'vieux', 'trop', 'même', 'elle', 'tous', 'là', 'quand', 'jusquà', 'utiliser', 
             'votre', 'manière', 'sur', 'beaucoup', 'puis', 'les', 'écrire', 'voudrais', 
             'comme', 'si', 'ces', 'son', 'long', 'faire', 'chose', 'voir', 'lui', 'deux', 
             'a', 'regarder', 'plus', 'jour', 'pourrait', 'aller', 'venir', 'fait', 'nombre', 
             'son', 'aucun', 'plus', 'personnes', 'ma', 'sur', 'savoir', 'eau', 'que', 'appel', 
             'première', 'qui', 'peut', 'vers le bas', 'côté', 'été', 'maintenant', 'trouver', 
             'tête', 'supporter', 'propre', 'page', 'devrait', 'pays', 'trouvé', 'réponse', 'école', 
             'croître', 'étude', 'encore', 'apprendre', 'usine', 'couvercle', 'nourriture', 'soleil', 
             'quatre', 'entre', 'état', 'garder', 'œil', 'jamais', 'dernier', 'laisser', 'pensée', 'ville', 
             'arbre', 'traverser', 'ferme', 'dur', 'début', 'puissance', 'histoire', 'scie', 'loin', 'mer', 
             'tirer', 'gauche', 'tard', 'courir', 'needs a context', 'tandis que', 'presse', 'proche', 'nuit', 
             'réel', 'vie', 'peu', 'nord', 'livre', 'porter', 'a pris', 'science', 'manger', 'chambre', 
             'ami', 'a commencé', 'idée', 'poisson', 'montagne', 'Arrêtez', 'une fois', 'base', 
             'entendre', 'cheval', 'coupe', 'sûr', 'regarder', 'couleur', 'face', 'bois', 'principal', 
             'ouvert', 'paraître', 'ensemble', 'suivant', 'blanc', 'enfants', 'commencer', 'eu', 
             'marcher', 'exemple', 'facilité', 'papier', 'groupe', 'toujours', 'musique', 
             'ceux', 'tous les deux', 'marque', 'souvent', 'lettre', 'jusqu’à ce que', 
             'mile', 'rivière', 'voiture', 'pieds', 'soins', 'deuxième']



#English Words List
eng_words = ['as', 'I', 'his', 'that', 'he', 'was', 'for', 'on', 'are', 'with', 'they', 'be', 
             'at', 'one', 'have', 'this', 'from', 'by', 'hot', 'word', 'but', 'what', 'some', 'is', 
             'it', 'you', 'or', 'had', 'the', 'of', 'to', 'and', 'a', 'in', 'we', 'can', 'out', 'other', 
             'were', 'which', 'do', 'their', 'time', 'if', 'will', 'how', 'said', 'an', 'each', 'tell',
             'does', 'set', 'three', 'want', 'air', 'well', 'also', 'play', 'small', 'end', 'put', 
             'home', 'read', 'hand', 'port', 'large', 'spell', 'add', 'even', 'land', 'here', 'must',
             'big', 'high', 'such', 'follow', 'act', 'why', 'ask', 'men', 'change', 'went', 'light',
             'kind', 'off', 'need', 'house', 'picture', 'try', 'us', 'again', 'animal', 'point', 
             'mother', 'world', 'near', 'build', 'self', 'earth', 'father', 'any', 'new', 'work', 
             'part', 'take', 'get', 'place', 'made', 'live', 'where', 'after', 'back', 'little',
             'only', 'round', 'man', 'year', 'came', 'show', 'every', 'good', 'me', 'give', 'our', 
             'under', 'name', 'very', 'through', 'just', 'form', 'sentence', 'great', 'think', 'say', 
             'help', 'low', 'line', 'differ', 'turn', 'cause', 'much', 'mean', 'before', 'move', 'right',
             'boy', 'old', 'too', 'same', 'she', 'all', 'there', 'when', 'up', 'use', 'your', 'way', 'about',
             'many', 'then', 'them', 'write', 'would', 'like', 'so', 'these', 'her', 'long', 'make', 'thing', 
             'see', 'him', 'two', 'has', 'look', 'more', 'day', 'could', 'go', 'come', 'did', 'number', 'sound',
             'no', 'most', 'people', 'my', 'over', 'know', 'water', 'than', 'call', 'first', 'who', 'may', 'down',
             'side', 'been', 'now', 'find', 'head', 'stand', 'own', 'page', 'should', 'country', 'found', 'answer',
             'school', 'grow', 'study', 'still', 'learn', 'plant', 'cover', 'food', 'sun', 'four', 'between',
             'state', 'keep', 'eye', 'never', 'last', 'let', 'thought', 'city', 'tree', 'cross', 'farm',
             'hard', 'start', 'might', 'story', 'saw', 'far', 'sea', 'draw', 'left', 'late', 'run', 'do not',
             'while', 'press', 'close', 'night', 'real', 'life', 'few', 'north', 'book', 'carry', 'took', 
             'science', 'eat', 'room', 'friend', 'began', 'idea', 'fish', 'mountain', 'stop', 'once',
             'base', 'hear', 'horse', 'cut', 'sure', 'watch', 'color', 'face', 'wood', 'main', 'open',
             'seem', 'together', 'next', 'white', 'children', 'begin', 'got', 'walk', 'example', 'ease',
             'paper', 'group', 'always', 'music', 'those', 'both', 'mark', 'often',
             'letter', 'until', 'mile', 'river', 'car', 'feet', 'care', 'second']